"""empty message

Revision ID: 1c0cebee6734
Revises: None
Create Date: 2017-10-21 15:30:06.712374

"""

# revision identifiers, used by Alembic.
revision = '1c0cebee6734'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newstag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('team', sa.Boolean(), nullable=False),
    sa.Column('wiki', sa.Boolean(), nullable=False),
    sa.Column('news', sa.Boolean(), nullable=False),
    sa.Column('translate', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('htuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_short', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('media', sa.String(length=1024), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('lastEdit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['htuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_short'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('valid_after', sa.DateTime(), nullable=False),
    sa.Column('valid_before', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['htuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_table('newscomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['htuser.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newstitle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('localized_title', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['newstag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('newstitle')
    op.drop_table('newscomment')
    op.drop_table('sessions')
    op.drop_table('news')
    op.drop_table('htuser')
    op.drop_table('permissions')
    op.drop_table('newstag')
    op.drop_table('languages')
    ### end Alembic commands ###
