"""empty message

Revision ID: 8191d829e5df
Revises: 1c0cebee6734
Create Date: 2017-11-05 13:54:33.914171

"""

# revision identifiers, used by Alembic.
revision = '8191d829e5df'
down_revision = '1c0cebee6734'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('valid_after', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('valid_before', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['htuser.id'], name='sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_uuid', name='sessions_session_uuid_key')
    )
    ### end Alembic commands ###
