"""empty message

Revision ID: base_create
Revises: None
Create Date: 2017-01-14 19:54:25.977529

"""

# revision identifiers, used by Alembic.
revision = 'base_create'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('newstag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.Column('master', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('team', sa.Boolean(), nullable=False),
    sa.Column('wiki', sa.Boolean(), nullable=False),
    sa.Column('news', sa.Boolean(), nullable=False),
    sa.Column('translate', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('permissions_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.permissions_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('news',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_short', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('media', sa.String(length=1024), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('lastEdit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_short'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('valid_after', sa.DateTime(), nullable=False),
    sa.Column('valid_before', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_table('newscomment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('newstitle',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('localized_title', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.post_id'], ),
    sa.PrimaryKeyConstraint('news_id', 'language_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.post_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['newstag.tag_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('newstitle')
    op.drop_table('newscomment')
    op.drop_table('sessions')
    op.drop_table('news')
    op.drop_table('user')
    op.drop_table('permissions')
    op.drop_table('newstag')
    op.drop_table('languages')
    ### end Alembic commands ###
