"""news_fix

Revision ID: e6aa10cb1598
Revises: base_create
Create Date: 2017-01-14 20:40:05.429731

"""

# revision identifiers, used by Alembic.
revision = 'e6aa10cb1598'
down_revision = 'base_create'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'language_code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'language_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    ### end Alembic commands ###
